ALTER TABLE backup_job
  ADD COLUMN retry_count INT NOT NULL DEFAULT 0,
  ADD COLUMN max_retries INT NOT NULL DEFAULT 0,
  ADD COLUMN error_message TEXT NULL,
  ADD COLUMN started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN ended_at DATETIME NULL,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE INDEX idx_backup_job_status_created_at ON backup_job (status, created_at);
